extends RefCounted
const Sh = preload("res://addons/addon_lib/gdsh/_ns/gd_sh.gd")
const Model = preload("res://addons/addon_lib/gdsh/src/ui/terminal_input.gd")
const TUIList = preload("res://tests/gdsh/fixtures/tui_list.gd")
var suite


func tree() -> SceneTree:
	return Engine.get_main_loop() as SceneTree


func frames() -> void:
	for frame in 3:
		await tree().process_frame


func key(code:int, unicode:=0, ctrl:=false, echo:=false, shift:=false, alt:=false, meta:=false) -> void:
	var event = InputEventKey.new()
	event.keycode = code
	event.unicode = unicode
	event.ctrl_pressed = ctrl
	event.echo = echo
	event.shift_pressed = shift
	event.alt_pressed = alt
	event.meta_pressed = meta
	event.pressed = true
	Input.parse_input_event(event)
	await frames()
	event = event.duplicate()
	event.pressed = false
	event.echo = false
	Input.parse_input_event(event)
	await frames()


func run(owner) -> void:
	suite = owner
	var model = Model.new()
	model.set_text("one/two three")
	model.move_to(7)
	suite.equal(model.word_left(), 4, "terminal word movement stops at path segment")
	model.replace(model.word_left(), model.caret, "")
	suite.equal(model.text, "one/ three", "terminal word deletion edits only the buffer")
	model.move_to(-10)
	model.replace(model.caret - 1, model.caret, "")
	suite.equal(model.text, "one/ three", "terminal backspace clamps at prompt boundary")
	model.insert("a\r\nb\rc\nd\te")
	suite.equal(model.text, "a\nb\nc\nd\teone/ three", "terminal paste preserves newlines and tabs")
	model.set_text("aé中")
	model.move_to(2)
	model.replace(model.caret - 1, model.caret, "")
	suite.equal(model.text, "a中", "terminal deletes a Unicode codepoint")
	model.move_to(900)
	model.replace(model.caret, model.caret + 1, "")
	suite.equal(model.text, "a中", "terminal delete clamps at end")

	var console = Sh.TerminalConsole.new()
	console.context.scopes["test_tui_list"] = {"script": TUIList}
	tree().root.add_child(console)
	console.size = Vector2(500, 220)
	await frames()
	console.focus_input()
	await frames()
	var prompt = "Console $ "
	suite.equal(console.output.get_parsed_text(), prompt, "terminal begins with one inline prompt")
	console.set_input_text("echo first")
	await key(KEY_ENTER, 0, false, false, true)
	await key(KEY_ENTER, 0, false, false, false, true)
	suite.equal(console.get_input_text(), "echo first\n\n", "both modified Enter shortcuts insert real newlines")
	var blank_rect = console.get_caret_rect()
	suite.check(blank_rect.size.y > 0 and blank_rect.position.y > 0, "trailing blank line has a caret")
	await key(KEY_X, 120)
	suite.equal(console.get_input_text(), "echo first\n\nx", "typing after blank lines preserves input")
	console.set_input_text("echo first\necho second")
	await key(KEY_HOME)
	suite.equal(console.input_model.caret, 11, "Home moves to logical line start")
	await key(KEY_RIGHT)
	await key(KEY_END)
	suite.equal(console.input_model.caret, 22, "End moves to logical line end")
	await key(KEY_HOME, 0, true)
	suite.equal(console.input_model.caret, 0, "Ctrl Home moves to whole buffer start")
	await key(KEY_END, 0, true)
	suite.equal(console.input_model.caret, 22, "Ctrl End moves to whole buffer end")
	await key(KEY_LEFT, 0, false, false, false, false, true)
	suite.equal(console.input_model.caret, 11, "Cmd Left moves to logical line start")
	await key(KEY_UP)
	suite.equal(console.input_model.caret, 0, "Up moves to preceding displayed row without entering prompt")
	await key(KEY_DOWN)
	suite.equal(console.input_model.caret, 11, "Down preserves preferred horizontal position when prompt clamps previous row")
	console.set_input_text("echo first\n\necho second\n")
	await frames()
	console.output.select_all()
	suite.equal(console.output.get_selected_text(), prompt + console.get_input_text(), "copy preserves real newlines without a synthetic caret")
	console.set_input_text("echo first\necho second")
	await key(KEY_ENTER)
	suite.equal(console.command_history.back(), "echo first\necho second", "multiline submission is one history entry")
	suite.check(console.output.get_parsed_text().contains("first\nsecond\n"), "multiline submission executes both commands")
	console.clear_output()
	console.set_input_text("draft")
	console.input_model.move_to(2)
	await key(KEY_UP)
	suite.equal(console.get_input_text(), "echo first\necho second", "Up at first input row recalls multiline history")
	await key(KEY_DOWN)
	suite.equal(console.get_input_text(), "draft", "Down past newest history restores draft")
	suite.equal(console.input_model.caret, 2, "history restores draft caret")
	await key(KEY_UP)
	await key(KEY_X, 120)
	suite.equal(console.command_history.back(), "echo first\necho second", "editing recalled input leaves stored history unchanged")
	console.clear_history()
	console.set_input_text("123456789012345\nx\n123456789012345\n")
	console.input_model.move_to(10)
	await frames()
	await key(KEY_DOWN)
	suite.equal(console.input_model.caret, 17, "vertical movement clamps on a short row")
	await key(KEY_DOWN)
	suite.equal(console.input_model.caret, 33, "vertical movement retains desired x after short row")
	await key(KEY_DOWN)
	suite.equal(console.input_model.caret, 34, "Down reaches a trailing empty line")
	await key(KEY_UP)
	suite.equal(console.input_model.caret, 33, "Up leaves trailing empty line with preferred x")
	console.set_input_text("echo " + "wrapped ".repeat(30))
	console.input_model.move_to(15)
	await frames()
	var first_row = console._caret_row()
	await key(KEY_DOWN)
	suite.equal(console._caret_row(), first_row + 1, "Down navigates soft wrapped rows")
	await key(KEY_UP)
	suite.equal(console.input_model.caret, 15, "wrapped vertical round trip retains horizontal position")
	console.clear_output()
	console.set_input_text("echo [color=red]literal[/color]")
	await frames()
	suite.equal(console.output.get_parsed_text(), prompt + console.get_input_text(), "terminal escapes BBCode in editable input")
	for value in ["e", "ec", "echo first", "echo second"]:
		console.set_input_text(value)
		await frames()
		suite.equal(console.output.get_parsed_text(), prompt + value, "terminal replaces only active paragraph: " + value)
	await key(KEY_HOME)
	await key(KEY_BACKSPACE)
	suite.equal(console.get_input_text(), "echo second", "focused terminal cannot delete prompt")
	await key(KEY_END)
	await key(KEY_X, 120)
	suite.equal(console.get_input_text(), "echo secondx", "focused terminal receives typed text")
	await key(KEY_BACKSPACE)
	await key(KEY_ENTER)
	suite.equal(console.output.get_parsed_text(), "Console $ echo second\nsecond\nConsole $ ", "terminal commits input once and restores prompt")
	suite.equal(console.get_input_text(), "", "terminal clears submitted buffer")
	await key(KEY_UP)
	suite.equal(console.get_input_text(), "echo second", "terminal history replaces the buffer")
	await key(KEY_DOWN)
	suite.equal(console.get_input_text(), "", "terminal history returns to empty input")
	var completed = console.output.get_parsed_text().trim_suffix(prompt)
	console.set_input_text("echo new")
	await frames()
	suite.equal(console.output.get_parsed_text(), completed + prompt + "echo new", "terminal editing retains completed scrollback")
	console.output.select_all()
	var selected = console.output.get_selected_text()
	console._blink.timeout.emit()
	await frames()
	suite.equal(console.output.get_selected_text(), selected, "terminal blink preserves native selection")
	suite.check(selected.ends_with("echo new") and not selected.contains("█"), "terminal copy includes input without synthetic cursor")
	await key(KEY_BACKSPACE)
	suite.equal(console.get_input_text(), "echo ne", "typing with selected transcript edits only the buffer")
	suite.equal(console.output.get_selected_text(), "", "editing clears copy selection")
	console.load("res://tests/gdsh/fixtures/commands/")
	console.set_input_text("pro")
	await console.request_completion()
	suite.check(console._popup != null and console._popup.visible, "terminal completion uses shared popup")
	if console._popup != null:
		console._popup.accept_selected()
		suite.equal(console.get_input_text(), "probe ", "terminal completion inserts at buffer caret")
	console.set_input_text("echo before\npro\necho after")
	console.input_model.move_to(15)
	await console.request_completion()
	if console._popup != null and console._popup.visible:
		console._popup.accept_selected()
		suite.equal(console.get_input_text(), "echo before\nprobe \necho after", "multiline completion edits only the token at caret")
	else:
		suite.check(false, "multiline completion finds command on second line")
	console.set_input_text("pro")
	console.request_completion()
	console.input_model.move_to(0)
	await frames()
	suite.check(console._popup == null or not console._popup.visible, "terminal caret movement invalidates pending completion")
	console.set_input_text("draft")
	await console.execute("clear")
	suite.equal(console.output.get_parsed_text(), prompt, "terminal clear retains exactly one new prompt")
	console.execution_handler = func(_text, ctx):
		ctx.append_output("no-newline")
	await console.execute("partial")
	suite.equal(console.output.get_parsed_text(), "Console $ partial\nno-newline\nConsole $ ", "terminal inserts boundary after output without newline")
	console.execution_handler = Callable()
	console.context.variables["$saved"] = "value"
	await console.execute("new_ctx")
	suite.check(not console.context.variables.has("$saved"), "terminal resets session")
	suite.check(console.output.get_parsed_text().ends_with("Console $ new_ctx\nConsole $ "), "terminal reset does not insert prompt before result")
	console.clear_output()
	console.execution_handler = func(_text, ctx):
		for i in 40:
			ctx.append_output("row-%02d\n" % i)
			await tree().process_frame
	console.execute("stream")
	for i in 25: await tree().process_frame
	var bar = console.output.get_v_scroll_bar()
	suite.check(bar.value > 0 and bar.value >= bar.max_value - bar.page - 24, "terminal follows live output at bottom")
	bar.value = 0
	for i in 25: await tree().process_frame
	suite.check(not console.is_busy and is_zero_approx(bar.value), "terminal preserves scrolled-back viewport through completion")
	var transcript = console.output.get_parsed_text()
	suite.check(transcript.count("row-00") == 1 and transcript.count("row-39") == 1, "terminal streaming does not duplicate result output")
	console.set_input_text("echo " + "long-input ".repeat(80))
	await frames()
	suite.check(bar.value > 0, "editing returns from scrollback to a wrapped input caret")
	console.input_model.move_to(0)
	await frames()
	suite.check(bar.value < bar.max_value - bar.page, "Home reveals start of input taller than viewport")
	console.set_input_text("echo row\n".repeat(40) + "\n")
	await frames()
	var final_caret = console.get_caret_rect()
	suite.check(final_caret.size.y > 0 and final_caret.position.y >= 0 and final_caret.end.y <= console.output.size.y, "trailing blank caret remains inside viewport after scrolling")
	await key(KEY_BACKSPACE)
	suite.equal(console.get_input_text(), "echo row\n".repeat(40), "Backspace joins a trailing empty line")
	console.set_prompt("[color=cyan]Test[/color] >")
	console.set_input_text("x")
	await frames()
	suite.check(console.output.get_parsed_text().ends_with("Test > x"), "terminal prompt changes preserve buffer and balanced tags")
	console.reset_prompt()
	console.execution_handler = Callable()
	console.context.scopes["test_tui_list"] = {"script": TUIList}
	console.execute("test_tui_list")
	await frames()
	suite.check(console.active_tui != null and console.is_busy and not console.output.visible, "terminal gives TUI display ownership")
	if console.active_tui != null:
		var refused = await console.execute("echo refused")
		suite.check(refused.exit_code != 0, "terminal refuses another submission while TUI is active")
		await key(KEY_ESCAPE)
		suite.check(console.active_tui == null and not console.is_busy and console.output.visible and console.output.has_focus(), "terminal restores display and focus after TUI")
		console.execute("test_tui_list")
		await frames()
		var session = console.active_tui
		console.queue_free()
		await frames()
		suite.check(not is_instance_valid(session) or session.is_closed, "closing terminal unwinds active TUI")
	else:
		console.queue_free()
		await frames()
